export { default as Main } from "./Main/Main"
export { default as Option } from "./Option/Option"
export { default as RulesModal } from "./Modals/RulesModal/RulesModal"
export { default as Header } from "./Header/Header"
export { default as Footer } from "./Footer/Footer"
export { default as PlayersOption } from "./PlayersOption/PlayersOption"
export { default as ComputersOption } from "./ComputersOption/ComputersOption"